"""Create car table

Revision ID: 8b169d5645cc
Revises: 
Create Date: 2018-12-13 01:24:48.543014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b169d5645cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_plate', sa.String(length=8), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('depart_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_depart_time'), 'car', ['depart_time'], unique=False)
    op.create_index(op.f('ix_car_entry_time'), 'car', ['entry_time'], unique=False)
    op.create_index(op.f('ix_car_number_plate'), 'car', ['number_plate'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_number_plate'), table_name='car')
    op.drop_index(op.f('ix_car_entry_time'), table_name='car')
    op.drop_index(op.f('ix_car_depart_time'), table_name='car')
    op.drop_table('car')
    # ### end Alembic commands ###
